/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as HospitaisRouteImport } from './routes/hospitais'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as MedicosIndexRouteImport } from './routes/medicos/index'
import { Route as MedicosIdRouteImport } from './routes/medicos/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitaisRoute = HospitaisRouteImport.update({
  id: '/hospitais',
  path: '/hospitais',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MedicosIndexRoute = MedicosIndexRouteImport.update({
  id: '/medicos/',
  path: '/medicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosIdRoute = MedicosIdRouteImport.update({
  id: '/medicos/$id',
  path: '/medicos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/hospitais': typeof HospitaisRoute
  '/vagas': typeof VagasRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/medicos/$id': typeof MedicosIdRoute
  '/medicos/': typeof MedicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/hospitais': typeof HospitaisRoute
  '/vagas': typeof VagasRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/medicos/$id': typeof MedicosIdRoute
  '/medicos': typeof MedicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/hospitais': typeof HospitaisRoute
  '/vagas': typeof VagasRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/medicos/$id': typeof MedicosIdRoute
  '/medicos/': typeof MedicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/contato'
    | '/hospitais'
    | '/vagas'
    | '/favoritos'
    | '/painel'
    | '/medicos/$id'
    | '/medicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/contato'
    | '/hospitais'
    | '/vagas'
    | '/favoritos'
    | '/painel'
    | '/medicos/$id'
    | '/medicos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/como-funciona'
    | '/contato'
    | '/hospitais'
    | '/vagas'
    | '/_authenticated/favoritos'
    | '/_authenticated/painel'
    | '/medicos/$id'
    | '/medicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  HospitaisRoute: typeof HospitaisRoute
  VagasRoute: typeof VagasRoute
  MedicosIdRoute: typeof MedicosIdRoute
  MedicosIndexRoute: typeof MedicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitais': {
      id: '/hospitais'
      path: '/hospitais'
      fullPath: '/hospitais'
      preLoaderRoute: typeof HospitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/medicos/': {
      id: '/medicos/'
      path: '/medicos'
      fullPath: '/medicos/'
      preLoaderRoute: typeof MedicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos/$id': {
      id: '/medicos/$id'
      path: '/medicos/$id'
      fullPath: '/medicos/$id'
      preLoaderRoute: typeof MedicosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  HospitaisRoute: HospitaisRoute,
  VagasRoute: VagasRoute,
  MedicosIdRoute: MedicosIdRoute,
  MedicosIndexRoute: MedicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
