-- SEED HOSPITALS AND HEALTH UNITS
-- Real public/university hospitals and reference private hospitals across
-- major Brazilian state capitals, so the platform launches with a populated
-- base of hospitals/units instead of an empty list. created_by is left NULL
-- (these were not registered by a specific platform user).
INSERT INTO public.hospitals (name, city, state, type) VALUES
  ('Hospital das Clínicas da FMUSP', 'São Paulo', 'SP', 'Hospital Universitário'),
  ('Hospital Israelita Albert Einstein', 'São Paulo', 'SP', 'Hospital Geral'),
  ('Hospital Sírio-Libanês', 'São Paulo', 'SP', 'Hospital Geral'),
  ('Santa Casa de Misericórdia de São Paulo', 'São Paulo', 'SP', 'Hospital Geral'),
  ('Instituto do Coração (InCor)', 'São Paulo', 'SP', 'Hospital Geral'),
  ('Hospital de Clínicas da Unicamp', 'Campinas', 'SP', 'Hospital Universitário'),
  ('Hospital das Clínicas de Ribeirão Preto (HCFMRP-USP)', 'Ribeirão Preto', 'SP', 'Hospital Universitário'),
  ('Hospital de Base de São José do Rio Preto', 'São José do Rio Preto', 'SP', 'Hospital Geral'),
  ('Hospital Universitário Clementino Fraga Filho (UFRJ)', 'Rio de Janeiro', 'RJ', 'Hospital Universitário'),
  ('Hospital Pedro Ernesto (UERJ)', 'Rio de Janeiro', 'RJ', 'Hospital Universitário'),
  ('Instituto Nacional de Câncer (INCA)', 'Rio de Janeiro', 'RJ', 'Hospital Geral'),
  ('Hospital Municipal Miguel Couto', 'Rio de Janeiro', 'RJ', 'Pronto-Socorro'),
  ('Hospital Universitário Antônio Pedro (UFF)', 'Niterói', 'RJ', 'Hospital Universitário'),
  ('Hospital das Clínicas da UFMG', 'Belo Horizonte', 'MG', 'Hospital Universitário'),
  ('Santa Casa de Belo Horizonte', 'Belo Horizonte', 'MG', 'Hospital Geral'),
  ('Hospital João XXIII', 'Belo Horizonte', 'MG', 'Pronto-Socorro'),
  ('Hospital Universitário de Uberlândia (UFU)', 'Uberlândia', 'MG', 'Hospital Universitário'),
  ('Hospital Geral Roberto Santos', 'Salvador', 'BA', 'Hospital Geral'),
  ('Complexo Hospitalar Universitário Prof. Edgard Santos (UFBA)', 'Salvador', 'BA', 'Hospital Universitário'),
  ('Hospital Santa Izabel', 'Salvador', 'BA', 'Hospital Geral'),
  ('Hospital das Clínicas da UFPE', 'Recife', 'PE', 'Hospital Universitário'),
  ('Hospital da Restauração', 'Recife', 'PE', 'Pronto-Socorro'),
  ('IMIP - Instituto de Medicina Integral Prof. Fernando Figueira', 'Recife', 'PE', 'Hospital Geral'),
  ('Hospital Universitário Walter Cantídio (UFC)', 'Fortaleza', 'CE', 'Hospital Universitário'),
  ('Instituto Doutor José Frota (IJF)', 'Fortaleza', 'CE', 'Pronto-Socorro'),
  ('Hospital Universitário de Brasília (HUB)', 'Brasília', 'DF', 'Hospital Universitário'),
  ('Hospital de Base do Distrito Federal', 'Brasília', 'DF', 'Hospital Geral'),
  ('Hospital de Clínicas da UFPR', 'Curitiba', 'PR', 'Hospital Universitário'),
  ('Hospital Pequeno Príncipe', 'Curitiba', 'PR', 'Hospital Geral'),
  ('Hospital do Trabalhador', 'Curitiba', 'PR', 'Pronto-Socorro'),
  ('Hospital de Clínicas de Porto Alegre (HCPA)', 'Porto Alegre', 'RS', 'Hospital Universitário'),
  ('Santa Casa de Porto Alegre', 'Porto Alegre', 'RS', 'Hospital Geral'),
  ('Hospital São Lucas da PUCRS', 'Porto Alegre', 'RS', 'Hospital Geral'),
  ('Hospital Universitário Getúlio Vargas (UFAM)', 'Manaus', 'AM', 'Hospital Universitário'),
  ('Hospital e Pronto-Socorro João Lúcio Pereira Machado', 'Manaus', 'AM', 'Pronto-Socorro'),
  ('Hospital Universitário João de Barros Barreto (UFPA)', 'Belém', 'PA', 'Hospital Universitário'),
  ('Hospital Ophir Loyola', 'Belém', 'PA', 'Hospital Geral'),
  ('Hospital das Clínicas da UFG', 'Goiânia', 'GO', 'Hospital Universitário'),
  ('Hospital de Urgências de Goiânia (HUGO)', 'Goiânia', 'GO', 'Pronto-Socorro'),
  ('Hospital Universitário Polydoro Ernani de São Thiago (UFSC)', 'Florianópolis', 'SC', 'Hospital Universitário'),
  ('Hospital Universitário Cassiano Antônio Moraes (UFES)', 'Vitória', 'ES', 'Hospital Universitário'),
  ('Hospital Universitário Lauro Wanderley (UFPB)', 'João Pessoa', 'PB', 'Hospital Universitário'),
  ('Hospital Universitário da UFMA (HUUFMA)', 'São Luís', 'MA', 'Hospital Universitário'),
  ('Hospital Universitário Onofre Lopes (UFRN)', 'Natal', 'RN', 'Hospital Universitário'),
  ('Hospital Universitário Maria Aparecida Pedrossian (UFMS)', 'Campo Grande', 'MS', 'Hospital Universitário'),
  ('Hospital Universitário Júlio Müller (UFMT)', 'Cuiabá', 'MT', 'Hospital Universitário')
ON CONFLICT DO NOTHING;
